[package]
name = "tether-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Tether client binary - the computer doing the viewing/controlling."

[dependencies]
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true

[lints]
workspace = true
