//! Shared NV12 plane helpers + a (test-only) software H.264 decoder via
//! ffmpeg's native `h264` decoder.
//!
//! Production builds hard-require the VAAPI hardware path — see
//! `crate::probe`. The SW decoder lives here behind `#[cfg(test)]` to feed
//! decode-path tests a real bitstream without a hardware device.
//!
//! There is no software *encoder*: tether links its own LGPL FFmpeg, which
//! has no libx264/libx265. Tests that need an H.264 bitstream read the
//! committed Annex-B fixture (`fixture_access_units` /
//! `testdata/h264_320x240_intra.bin`, regenerated by
//! `scripts/gen-codec-fixtures.sh`) rather than encoding on the fly.

use std::slice;

use rsmpeg::avcodec::AVPacket;
use rsmpeg::avutil::AVFrame;
use rsmpeg::error::RsmpegError;
use rsmpeg::ffi;

use crate::{CodecError, Result};

#[cfg(test)]
use rsmpeg::avcodec::{AVCodec, AVCodecContext};
#[cfg(test)]
use tether_protocol::control::CodecKind;
#[cfg(test)]
use crate::{init_ffmpeg, DecodedFrame, Decoder, Frame};

/// Pack a planar AVFrame plane into a tight `Vec<u8>`, stripping any
/// stride padding so downstream consumers can upload row-major without
/// per-row math.
#[cfg(test)]
pub(crate) fn pack_plane(plane: &[u8], stride: usize, row_bytes: usize, height: usize) -> Vec<u8> {
    let mut packed = Vec::with_capacity(row_bytes * height);
    if stride == row_bytes {
        packed.extend_from_slice(&plane[..row_bytes * height]);
    } else {
        for row in 0..height {
            let start = row * stride;
            packed.extend_from_slice(&plane[start..start + row_bytes]);
        }
    }
    packed
}

/// Interleave two single-channel chroma planes (YUV420P layout) into
/// an NV12-shaped UV buffer (U₀ V₀ U₁ V₁ ...). Output is tight (no
/// stride padding) and sized `chroma_w * chroma_h * 2` bytes — twice
/// the input plane size, since each chroma sample contributes one byte
/// of U and one of V. Replaces the per-plane swscale we used to do
/// after the VAAPI decoder; for the software path this is a fast
/// memory-bound shuffle (no resampling).
#[cfg(test)]
pub(crate) fn interleave_uv(
    u: &[u8],
    u_stride: usize,
    v: &[u8],
    v_stride: usize,
    chroma_w: usize,
    chroma_h: usize,
) -> Vec<u8> {
    let mut uv = Vec::with_capacity(chroma_w * chroma_h * 2);
    for row in 0..chroma_h {
        let u_row = &u[row * u_stride..row * u_stride + chroma_w];
        let v_row = &v[row * v_stride..row * v_stride + chroma_w];
        for col in 0..chroma_w {
            uv.push(u_row[col]);
            uv.push(v_row[col]);
        }
    }
    uv
}

/// Borrow plane `idx` of an allocated `AVFrame` as `&mut [u8]` covering
/// `linesize[idx] * height` bytes. Encapsulates the one unsafe slice
/// construction we need against rsmpeg's raw-pointer frame layout —
/// the mutable borrow of `frame` keeps the underlying buffer alive for
/// the slice's lifetime.
#[allow(clippy::cast_sign_loss)] // ffmpeg linesize is i32 but non-negative for allocated frames
pub(crate) fn frame_plane_mut(frame: &mut AVFrame, idx: usize, height: usize) -> &mut [u8] {
    let stride = frame.linesize[idx] as usize;
    let ptr = frame.data_mut()[idx];
    // SAFETY: caller asserts `frame` was constructed with a successful
    // alloc_buffer() at width/height matching `linesize[idx]` / `height`,
    // so plane `idx` is backed by at least `stride * height` valid bytes.
    // The &mut borrow on `frame` is held for the slice's lifetime,
    // preventing reallocation underneath us.
    unsafe { slice::from_raw_parts_mut(ptr, stride * height) }
}

/// Borrow plane `idx` of an allocated `AVFrame` as a read-only slice.
#[allow(clippy::cast_sign_loss)] // ffmpeg linesize is i32 but non-negative for allocated frames
#[cfg(test)]
pub(crate) fn frame_plane(frame: &AVFrame, idx: usize, height: usize) -> &[u8] {
    let stride = frame.linesize[idx] as usize;
    let ptr = frame.data[idx];
    // SAFETY: same rationale as `frame_plane_mut`; the &AVFrame borrow
    // keeps the buffer alive.
    unsafe { slice::from_raw_parts(ptr, stride * height) }
}

/// Wrap a slice of encoded bytes in an `AVPacket` owned by ffmpeg so it
/// can be fed to a decoder. rsmpeg doesn't expose a safe helper for
/// this — we allocate via `av_new_packet` (so the packet owns its
/// buffer and frees it on Drop) and memcpy our bytes in.
pub(crate) fn packet_from_bytes(bytes: &[u8]) -> Result<AVPacket> {
    let mut packet = AVPacket::new();
    let size = i32::try_from(bytes.len()).map_err(|_| {
        CodecError::Ffmpeg(RsmpegError::AVError(ffi::AVERROR_INVALIDDATA))
    })?;
    // SAFETY: `packet` was just allocated by AVPacket::new(). av_new_packet
    // allocates `size + AV_INPUT_BUFFER_PADDING_SIZE` bytes, fills the
    // padding with zeroes, and sets packet.data + packet.size. Ownership
    // of the buffer transfers to the packet, freed by AVPacket's Drop
    // impl via av_packet_free.
    let ret = unsafe { ffi::av_new_packet(packet.as_mut_ptr(), size) };
    if ret < 0 {
        return Err(CodecError::Ffmpeg(RsmpegError::AVError(ret)));
    }
    // SAFETY: packet.data now points to an owned buffer of exactly
    // `size` writable bytes (plus padding we don't touch).
    unsafe {
        std::ptr::copy_nonoverlapping(bytes.as_ptr(), packet.data, bytes.len());
    }
    Ok(packet)
}

/// A committed 320×240 H.264 Annex-B bitstream for decode-path tests.
///
/// tether links an LGPL FFmpeg with no software H.264 *encoder*, so tests
/// can't encode on the fly; they feed this pre-encoded fixture to the
/// (still-present) software and VAAPI decoders. Layout: repeated
/// `[u32-le length][access-unit bytes]`, one self-contained access unit
/// (AUD + SPS + PPS + IDR) per entry. Regenerate with
/// `scripts/gen-codec-fixtures.sh`.
#[cfg(test)]
pub(crate) const H264_320X240_INTRA: &[u8] =
    include_bytes!("../testdata/h264_320x240_intra.bin");

/// Split the length-delimited fixture into its access units. Each unit is
/// independently decodable, so a parser-less decoder can be fed one at a time
/// (mirroring how the encoder used to hand out one packet per frame).
#[cfg(test)]
pub(crate) fn fixture_access_units(fixture: &[u8]) -> Vec<&[u8]> {
    let mut units = Vec::new();
    let mut i = 0;
    while i + 4 <= fixture.len() {
        let len = u32::from_le_bytes(fixture[i..i + 4].try_into().unwrap()) as usize;
        i += 4;
        assert!(i + len <= fixture.len(), "truncated fixture access unit");
        units.push(&fixture[i..i + len]);
        i += len;
    }
    // A correctly-formed fixture consumes exactly to the end; trailing bytes
    // mean truncation at a length boundary, which would otherwise silently
    // yield fewer access units than intended.
    assert_eq!(i, fixture.len(), "fixture has trailing bytes after last access unit");
    units
}

// Software H.264 decoder. Test-only: production builds hard-require the VAAPI
// hardware path via `crate::probe::build_decoder`, so this struct exists only
// to decode the committed fixture above without a hardware device. (ffmpeg's
// native H.264 *decoder* is in the LGPL build; only the encoder is not.)
#[cfg(test)]
pub(crate) struct H264Decoder {
    decoder: AVCodecContext,
}

// SAFETY: ffmpeg's decoder context is safe to MOVE between threads but not to
// SHARE; we expose only `&mut self` methods, so the borrow checker serialises
// access within a thread and we never alias the inner pointer.
#[cfg(test)]
unsafe impl Send for H264Decoder {}

#[cfg(test)]
impl H264Decoder {
    pub fn new() -> Result<Self> {
        init_ffmpeg();
        let codec = AVCodec::find_decoder(ffi::AV_CODEC_ID_H264)
            .ok_or(CodecError::CodecNotFound("h264"))?;
        let mut decoder = AVCodecContext::new(&codec);
        decoder.open(None)?;
        Ok(Self { decoder })
    }
}

#[cfg(test)]
impl Decoder for H264Decoder {
    fn submit(&mut self, encoded: &[u8]) -> Result<()> {
        if encoded.is_empty() {
            return Ok(());
        }
        let packet = packet_from_bytes(encoded)?;
        self.decoder.send_packet(Some(&packet))?;
        Ok(())
    }

    // Same rationale as encode_bgra: ffmpeg's i32 width/height/linesize
    // on an allocated decoder output frame are non-negative.
    #[allow(clippy::cast_sign_loss)]
    fn next_frame(&mut self) -> Result<Option<Frame>> {
        let yuv = match self.decoder.receive_frame() {
            Ok(f) => f,
            Err(RsmpegError::DecoderDrainError | RsmpegError::DecoderFlushedError) => {
                return Ok(None)
            }
            Err(e) => return Err(CodecError::Ffmpeg(e)),
        };
        // H264 in our configuration always emits YUV420P. If a
        // future capture path negotiates something else (NV12,
        // YUV422) the renderer's YUV→RGB shader will need
        // companion shaders / upload paths; for now reject loudly
        // so the failure is observable instead of a silent garble.
        if yuv.format != ffi::AV_PIX_FMT_YUV420P {
            return Err(CodecError::UnsupportedInputFormat);
        }
        let w = yuv.width as usize;
        let h = yuv.height as usize;
        let chroma_w = w.div_ceil(2);
        let chroma_h = h.div_ceil(2);
        let y_plane = pack_plane(frame_plane(&yuv, 0, h), yuv.linesize[0] as usize, w, h);
        // Interleave U + V into NV12-layout UV plane so the rest of
        // the pipeline (including the renderer) sees the same shape
        // VAAPI hardware decode produces natively. The interleave is
        // a byte permutation — no resampling, ~chroma_w*chroma_h
        // memory writes — and replaces the older path that uploaded
        // U and V as separate textures.
        let uv_plane = interleave_uv(
            frame_plane(&yuv, 1, chroma_h),
            yuv.linesize[1] as usize,
            frame_plane(&yuv, 2, chroma_h),
            yuv.linesize[2] as usize,
            chroma_w,
            chroma_h,
        );
        let pts_out = if yuv.pts == ffi::AV_NOPTS_VALUE {
            None
        } else {
            Some(yuv.pts)
        };
        Ok(Some(Frame::Cpu(DecodedFrame {
            width: yuv.width as u32,
            height: yuv.height as u32,
            pts: pts_out,
            y: y_plane,
            uv: uv_plane,
        })))
    }

    fn codec_kind(&self) -> CodecKind {
        CodecKind::H264
    }

    fn name(&self) -> &'static str {
        "libavcodec h264 sw"
    }
}

#[cfg(test)]
#[allow(
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::cast_lossless
)]
mod tests {
    use super::*;

    /// Verifies `interleave_uv` produces the correct NV12 byte order
    /// (U₀ V₀ U₁ V₁ ...) and correctly strips stride padding. The
    /// stride case matters because ffmpeg-allocated YUV420P frames
    /// typically have linesize > chroma_w, and a regression here
    /// would silently shift chroma samples (visible as wrong colors
    /// per row) instead of erroring.
    #[test]
    fn interleave_uv_packs_nv12_and_strips_stride() {
        // 4x2 chroma plane with stride 6 (2 bytes of trailing padding
        // per row). U byte values encode (row << 4) | col so any
        // mis-indexing is obvious.
        let chroma_w = 4;
        let chroma_h = 2;
        let stride = 6;
        let mut u_plane = vec![0u8; stride * chroma_h];
        let mut v_plane = vec![0u8; stride * chroma_h];
        for row in 0..chroma_h {
            for col in 0..chroma_w {
                u_plane[row * stride + col] = ((row << 4) | col) as u8;
                v_plane[row * stride + col] = 0xF0 | (((row << 4) | col) & 0x0F) as u8;
            }
            // Sentinel bytes in the stride padding region — should
            // never appear in the output.
            u_plane[row * stride + 4] = 0xAA;
            u_plane[row * stride + 5] = 0xAA;
            v_plane[row * stride + 4] = 0xAA;
            v_plane[row * stride + 5] = 0xAA;
        }

        let uv = interleave_uv(&u_plane, stride, &v_plane, stride, chroma_w, chroma_h);

        assert_eq!(uv.len(), chroma_w * chroma_h * 2);
        // Row 0: U(0,0) V(0,0) U(0,1) V(0,1) U(0,2) V(0,2) U(0,3) V(0,3)
        // Row 1: U(1,0) V(1,0) U(1,1) V(1,1) ...
        let expected: Vec<u8> = vec![
            0x00, 0xF0, 0x01, 0xF1, 0x02, 0xF2, 0x03, 0xF3,
            0x10, 0xF0, 0x11, 0xF1, 0x12, 0xF2, 0x13, 0xF3,
        ];
        assert_eq!(uv, expected);
        // No stride-padding sentinels leaked into the output.
        assert!(!uv.contains(&0xAA), "stride padding leaked into UV plane");
    }

    #[test]
    fn decodes_committed_h264_fixture_to_a_frame() {
        // tether's LGPL FFmpeg has no software H.264 encoder, so feed the
        // native decoder a pre-encoded 320×240 bitstream rather than encoding
        // here. Asserts the wrapper's YUV420P → NV12-shaped plane packing.
        let w = 320;
        let h = 240;
        let mut dec = H264Decoder::new().expect("decoder");

        let mut got = None;
        for au in fixture_access_units(H264_320X240_INTRA) {
            dec.submit(au).expect("submit");
            while let Some(f) = dec.next_frame().expect("next_frame") {
                let Frame::Cpu(f) = f else {
                    panic!("H264Decoder is SW-only and must never emit Gpu");
                };
                got = Some(f);
            }
        }
        let frame = got.expect("decoder produced a frame from the fixture");
        assert_eq!(frame.width, w);
        assert_eq!(frame.height, h);
        // NV12 plane sizes: Y is full res; UV is quarter-resolution
        // chroma but with two bytes per sample (interleaved U + V), so
        // the byte total matches the old U+V combined.
        let (cw, ch) = frame.chroma_dims();
        assert_eq!(frame.y.len(), (w * h) as usize);
        assert_eq!(frame.uv.len(), (cw * ch * 2) as usize);
    }
}
